sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -f Dockerfile.dev -t cberd1509/docker-react .

script:
  - docker run -e CI=true cberd1509/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-sa-east-1-532928905538"
  bucker_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KET"
  on:
    branch: master