language: generic
services: 
  - docker

before_install:
  - docker build -f Dockerfile.dev -t cberd1509/docker-react .

script:
  - docker run -e CI=true cberd1509/docker-react npm run test

deploy:
  
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "eb-tutorial"
  env: "eb-tutorial-dev"
  bucket_name: "elasticbeanstalk-sa-east-1-532928905538"
  bucket_path: "eb-tutorial"
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  on:
    branch: master
