version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - 3000:3000
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","run","test"]